### ISSUE TITLE
Base controller

### ISSUE THREAD

**Issue by drusixtynine** [webvimark/user-management#136]
Hi and thanks for this extension,
I am new in yii and I tried to install yii2basic and this user management extension, I followed everything according to the configuration process, but I can't figure out what is '4) In you base controller'? Did you mean in your base controller? which base controller, I don't see any?

Also, when installing this extension, the main public page of the application does not want to show without logging in, is that correct? is it configurable?

Thanks

**Comment by drusixtynine** [comment]
no answer anyone?

**Comment by ianpierreg** [comment]
drusixtynine, I ran into the same problem and couldn't find a solution. One way to solve the problem (not the best way) is to paste that part in every controller you create.

**Comment by webvimark** [comment]
Hi, actually by **base controller** I meant some controller that you use as parent class for every other controller. It's useful, because you can add some common functions or properties there.

For example:

```php
ShopController extends MyCoolController 
{
}

ProductsController extends MyCoolController 
{
}

CartController extends MyCoolController 
{
}
```

Where **MyCoolController** can be in *components* folder and have some common stuff.

But if you don't have such controller, then you may add this extension to every controller as @ianpierreg said

**Comment by drusixtynine** [comment]
wow, ok, thanks for this answer

For the main page, what I found is to do that through the permissions. I guess this is the correct way.

I am closing this thread, thanks guys
