### ISSUE TITLE
Permission are not working

### ISSUE THREAD

**Issue by shahzada-saddam** [webvimark/user-management#23]
Hi I have just setup your user-management module it is working fine on backend but not working on frontend for users. And how can i get rid of the defualt acces filters of yii2. 
And one more thing is how can i add new routes.

Thanks and Regards
Saddam Shahzad

**Comment by webvimark** [comment]
Hi, this module has not full support for "advanced" project structure where you have "front" and "backend" parts, because it's basically 2 different applications.

But you can try to do it following way:
1) Configure this module in "front" config and "backend" config
2) Use different table prefix in front and backend config (90% that it'll work) OR  if you want same "user" table then specify different "auth_assignment_table" (90% that it will *not* work :) )

**Comment by kchandrap** [comment]
How can we configure access control or permissions  globally for all controller in Yii2 ? and where we can define if session out then every action will redirect on login screen, Thanks
