### ISSUE TITLE
Sapare users in the back and the front end access

### ISSUE THREAD

**Issue by lukBarros** [webvimark/user-management#88]
Sapare users in the back and the front end access

Hi 2 users, user A only access backend and user B only access frontend in my yii2 advanced app.

The 2 users is status active. The 2 users login in the back and de frontend parts on my yii2 app.

Solutions for it???

**Comment by webvimark** [comment]
Sorry, but I've never used "advanced" structure, because it's basically 2 different applications with the same database. So there is no simple solution for it :)

You may try to update this module (I've added ability to refresh routes without deleting unused ones), then add it to frontend and backend, then refresh routes in both applications and assign permissions.
Not sure if this will work though :)

**Comment by lukBarros** [comment]
See

https://github.com/webvimark/user-management/pull/75

@janfrs write about it in the PR
